spring:
  # 数据源
  datasource:
    dynamic:
      primary: test_ddd_demo
      strict: false
      datasource:
        test_ddd_demo:
          url: jdbc:mysql://localhost:3306/test_ddd_demo?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8
          username: root
          password: yss123456
          type: com.alibaba.druid.pool.DruidDataSource
          # 连接池
          druid:
            initialSize: 5
            minIdle: 10
            maxActive: 20
            maxWait: 60000
            timeBetweenEvictionRunsMillis: 2000
            minEvictableIdleTimeMillis: 600000
            maxEvictableIdleTimeMillis: 900000
            maxOpenPreparedStatements: 20
            poolPreparedStatements: true
            maxPoolPreparedStatementPerConnectionSize: 100
            testWhileIdle: true
            testOnBorrow: false
            filters: stat,log4j,sql
# 日志
logging:
  file:
    path: logs/ddd-demo
  level:
    root: info
